### ISSUE TITLE
Mac OSX NSScreen assertion after Pangolin runs for a few seconds.

### ISSUE THREAD

**Issue by apatzer** [stevenlovegrove/Pangolin#111]
I'm using LSD_SLAM with a Pangolin display on a Mac. It only seems to work within an XQuartz window with FreeGlut (-DFORCE_GLUT=ON).

After a few seconds of operation, I get a windowing error (see below), that seems to have something to do with the window either redrawing itself, or refreshing itself based on other screen activity.

There's not much online for this error, and it's OSX specific. I'm hoping someone has encountered this (and knows how to solve it)?

I've tried rewriting the system so that the main thread sets up the Pangolin windows, but that doesn't seem to help.

```
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSScreen reconfig must only happen on the main thread.'

        3   Foundation                          0x00007fff855567d6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
        4   AppKit                              0x00007fff8457eaf4 +[NSScreen _invalidateIfNeededForReason:] + 153
        5   AppKit                              0x00007fff845a8acc -[NSApplication _reactToDockChanged] + 46
        6   AppKit                              0x00007fff84535670 _NSCoreDockMessageReceive + 803
        7   HIToolbox                           0x00007fff9380b190 _ZL12DockCallbackjjPvS_ + 2256
        8   HIServices                          0x00007fff8d264765 dockClientNotificationProc + 171
        9   CoreGraphics                        0x00007fff90997f80 _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 864
        10  CoreGraphics                        0x00007fff90995092 _ZN21CGSDatagramReadStream18dispatch_datagramsEv + 1134
        11  CoreGraphics                        0x00007fff90994b78 CGSDatagramReadStreamDispatchDatagramsWithData + 271
        12  CoreGraphics                        0x00007fff909949f7 CGSSnarfAndDispatchDatagrams + 1079
        13  CoreGraphics                        0x00007fff909943e2 CGSGetNextEventRecordInternal + 84
        14  CoreGraphics                        0x00007fff909942dc CGEventCreateNextEvent + 50
        15  libXplugin.1.dylib                  0x0000000108f20eca ___xp_init_service_cg_event_port_block_invoke + 106
```

**Comment by stevenlovegrove** [comment]
If OpenGL calls are made from multiple threads, you must be very careful. An OpenGL context is thread specific. For Pangolin, this means that you must call BindToContext in order to attach the context to the current thread, but this will detach it from other threads, so this must be called every time you switch. OSX is even more fussy - the safest thing to do is keep all OpenGL calls in the 'main' thread.

**Comment by cvcore** [comment]
I also bumped into this issue today while trying ORB_SLAM2. The program crashes with 
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'` after calling `pangolin::CreateWindowAndBind("ORB-SLAM2: Map Viewer",1024,768);`

any updates?

**Comment by smallzhan** [comment]
same error here with orb_slam2.

**Comment by smallzhan** [comment]
The problem can be solved by https://github.com/raulmur/ORB_SLAM2/pull/179  on the ORB_SLAM2 repo. @cvcore

**Comment by cvcore** [comment]
@smallzhan thanks, man! i ended up using that too!
