### ISSUE TITLE
PixelFormat error during installation phase

### ISSUE THREAD

**Issue by kerolex** [stevenlovegrove/Pangolin#131]
When running make -j4, I get this error:
```
../Pangolin/include/pangolin/video/drivers/ffmpeg.h:94:5: error: 'PixelFormat' does not a name a type
PixelFormat fmtout;
../Pangolin/include/pangolin/video/drivers/ffmpeg.h:142:5: error: 'PixelFormat' does not a name a type
PixelFormat fmtsrc;
../Pangolin/include/pangolin/video/drivers/ffmpeg.h:143:5: error: 'PixelFormat' does not a name a type
PixelFormat fmtdst;
```

I checked the FFMPEG libraries included in ffmpeg.h, but I can't find any definition of PixelFormat. 
I have FFMPEG version 3.0.2 on Ubuntu 14.04 LTS 64-bit.

Please let me know if you know the reason of such an error or if you need more details.

**Comment by stevenlovegrove** [comment]
If you don't need the functionality of FFMPEG (grabbing avi / mov / mpeg videos etc), you can disable it by clearing it's cmake variable (e.g. see issue https://github.com/stevenlovegrove/Pangolin/issues/118). If you do need to use it, you could try looking at this thread: https://github.com/stevenlovegrove/Pangolin/issues/27

You could also see if the devel branch works any better for you. Supporting ffmpeg has been very tricky due to the libav / ffmpeg fork a few years back and their quickly changing API.

**Comment by stevenlovegrove** [comment]
In particular, the fix should already be in the devel branch (https://github.com/stevenlovegrove/Pangolin/commit/2e5df57739aa57021828ca74dd3f72c2fbae4bbe)

**Comment by kerolex** [comment]
Thanks a lot for the quick answer. Thread #27 was exactly the answer I needed and I didn't notice before.
