### ISSUE TITLE
Can I use Pangolin in windows7 or other plantform

### ISSUE THREAD

**Issue by xiaozhuka** [stevenlovegrove/Pangolin#137]
as we knew, Pangolin is used in linux, but I find the following sentence is Readme.md
"It also enables write-once code for a number of platforms, currently including Windows, Linux, OSX, Android and IOS."
But when CMake in windows, there is a error
error: could not find git for clone of __glew

**Comment by stevenlovegrove** [comment]
Yes, it should work. It is used quite regularly on Windows, OSX and Linux (though bugs do sometimes creep through in some configurations). The file https://github.com/stevenlovegrove/Pangolin/blob/master/external/CMakeLists.txt attempts to download some dependent libraries on Windows to make it easier. For you, it appears the glew repository is inaccessible for some reason. You should see if you can access https://github.com/Perlmint/glew-cmake.git

If you are not able to debug that, then you can disable BUILD_EXTERN_GLEW in cmake and build that library separately and help Pangolins CMake process to find it.

**Comment by stevenlovegrove** [comment]
Did you make any progress? If not I'll keep the issue open

**Comment by huangju91** [comment]
I met the same error, and did what stevenlovegrove said ,but failed with new" error: could not find git for clone of __zlib"

**Comment by stevenlovegrove** [comment]
My advice is similar for zlib. Pangolin is trying to clone zlib (https://github.com/madler/zlib) using git which is failing. You can install zlib and the other dependencies manually or turn them off (BUILD_EXTERN_GLEW=false BUILD_EXTERN_LIBPNG=false BUILD_EXTERN_LIBJPEG=false). I'm guessing the clone is failing because you got Pangolin via zip, and you do not have GIT for windows (e.g. https://git-for-windows.github.io/)?

**Comment by huangju91** [comment]
@stevenlovegrove Thank you very much! Git  and cmake are new things for me, I dont't know it failed because I don't get GIT for windows. Reading  your explaination, it occurs to me that I cannot zip Pangolin in windows, so I copied one from unbuntu. Now I am going to follow what you said "urn them off (BUILD_EXTERN_GLEW=false BUILD_EXTERN_LIBPNG=false BUILD_EXTERN_LIBJPEG=false)" ,but I 'm afraid it will affect pangolin's function.
Thank you!Thank you! Thank you! Something repeated Three times is important.
