### ISSUE TITLE
Rendering issues with GlTextureCudaArray

### ISSUE THREAD

**Issue by stotko** [stevenlovegrove/Pangolin#161]
I am having problems with pangolin::GlTextureCudaArray`. In my viewer class, I want to display some rendered images. Below is the currently working code:

```
// --- MyViewer definition ---
uint8_t* image_buffer;
uint8_t* device_image_buffer;
pangolin::GlTexture image_texture;
pangolin::View viewport;

...

// --- MyViewer Contructor ---
image_buffer = new uint8_t[3 * 640 * 480];
// Initialize device_image_buffer via cudaMalloc(...)
image_texture.Reinitialise(640, 480, GL_RGB, false, 0, GL_RGB, GL_UNSIGNED_BYTE);
// Initialize viewport -> viewport = pangolin::Display(...)

...

// --- Render Function ---
// Write some data into device_image_buffer
// Copy data from device_image_buffer into image_buffer
image_texture.Upload(image_buffer , GL_RGB , GL_UNSIGNED_BYTE);
viewport.Activate();
image_texture.RenderToViewportFlipY();
```

The main goal here is that the rendered image (e.g. displaying a depth map) is given in `device_image_buffer` which is allocated in GPU memory. Then, this is copied back to CPU memory (`image_buffer`) and given to Pangolin which uploads it back to the GPU and then renders it.

In my real-time application, the viewer becomes more and more the bottleneck (with several of such viewports), so I tried to overcome the copy step to CPU memory. Inspired by https://github.com/arpg/Kangaroo/blob/master/applications/examples/Anaglyph.cpp, I have tested this code path:

```
// --- MyViewer definition ---
uint8_t* device_image_buffer;
pangolin::GlTextureCudaArray device_image_texture;
pangolin::View viewport;

...

// --- MyViewer Contructor ---
// Initialize device_image_buffer via cudaMalloc(...)
device_image_texture.Reinitialise(640, 480, GL_RGB, false, 0, GL_RGB, GL_UNSIGNED_BYTE);
// Initialize viewport -> viewport = pangolin::Display(...)

...

// --- Render Function ---
// Write some data into device_image_buffer
pangolin::CopyDevMemtoTex(device_image_buffer, 3 * 640 * sizeof(uint8_t), device_image_texture);
viewport.Activate();
device_image_texture.RenderToViewportFlipY();
```

Unfortunately, this does not work at all. Only a small part at the left of the Viewport is rendered correctly, while most of the rendering is a huge bulk of noise. I think, only the left part is updated correctly whereas the rest is not updated and shows the initial "state" of the array after allocation.

I know that there are some problems with the CUDA binding (https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/glcuda.h#L72), but I think this should work. The problematic line is the copy step with `pangolin::CopyDevMemtoTex()`. I also tested my own stuff and this works as expected, so it is some Pangolin related error (or something with CUDA itself?)

If it helps, I am using a Nvidia GTX Titan X with CUDA 8.0 on (K)Ubuntu 14.04.

**Comment by stevenlovegrove** [comment]
Have you noticed the typeof(T) in the implementation of CopyDevMemtoTex? T is the ptr type which is being automatically inferred from your code as uint8_t, but is used as the pixel element type to calculate line width, which should be uchar3 for this to work as intended, I think. You can use pangolin::CopyDevMemtoTex<uchar3>( (uchar3*)..., ..., ...) to fix your problem I think.

**Comment by RealRecon** [comment]
Yes, I think that I understand what you mean. The width parameter needed by `cudaMemcpy2DToArray` should be `3 * 640` but is inferred as `640` from `tex.width*sizeof(T)` since `T = uint8_t`. I will try your suggestion when I am back in the office.

Maybe, the function itself can be improved a little bit. From my opinion it would make more sense to use `tex.width*sizeBytes` where `sizeBytes`is inferred from `GL_RGB` and `GL_UNSIGNED_BYTE` using something like https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/gl.hpp#L64-L87. The pointer `T* d_img` itself is only passed to the copy function and implicitely converted to `void*`. So CUDA expects that the pitch and width are properly computed so that the "real" type of `d_img` is not needed.

**Comment by RealRecon** [comment]
I tested your suggestion and it helped a little bit. However, it still looks wrong. Here is an example captured by a Kinect v2 (preprocessed by myself before given to Pangolin, so ignore the black regions):

GlTexture:
![gltexture](https://cloud.githubusercontent.com/assets/9284226/19429920/73a88738-9452-11e6-8288-925476462411.png)

GlTextureCudaArray:
![gltexturecudaarray](https://cloud.githubusercontent.com/assets/9284226/19429922/7591382e-9452-11e6-99df-054f22a83414.png)

There seems to be a problem with the alignment because the right fourth is not updated at all ("initial memory state") and the whole image is stretched to the left part. The colors also are broken.

**Comment by stevenlovegrove** [comment]
I forgot to follow up on this issue. Did you manage to solve your problem in the end?

**Comment by RealRecon** [comment]
Unfortunatly, no. I'm still forced to use the slower path through the CPU. I also haven't tested it again with the current master build, but I expect the issue is still present.
Any new ideas on what I should try?

**Comment by RealRecon** [comment]
I have tested it again and now it is completely broken. Of course, I am using the version with `uchar3` as you have suggested.

I also tried to run the CUDA SDK samples and apparently they all work fine (despite some strange compilation problems of some unrelated ones). Also this here http://stackoverflow.com/a/12575567 works fine too.
All of them have in common that they use GLUT (maybe just for convenience). They also use buffers instead of textures and directly into the mapped device pointer rather than trying to copying.

Since I have no experience with OpenGL, it is almost impossible for me to debug Pangolin without help (this is one reason why I am using your library). Maybe, I should try `CopyPboToTex` but the declaration https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/glcuda.h#L101 does not match the definition https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/gl/glcuda.h#L234. I am also not totally sure what `buffer_layout` and `buffer_data_type` are and how to use them.

BTW, does the interoperability (and my use case) work on your machine?

**Comment by RealRecon** [comment]
I tried something else and it worked ... yes :)

If you consider this page here http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__OPENGL.html, you can see that `cudaGraphicsGLRegisterImage` does not support `GL_RGB` but `GL_RGBA8`. So I changed my "shaders" to use an alpha value of `255` for all values and extended my device buffer to something like `uchar4`. Now I get the correct renderings.
