### ISSUE TITLE
Can't find cmake file

### ISSUE THREAD

**Issue by Hoototo** [stevenlovegrove/Pangolin#185]
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Build type: Release
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Using flag -std=c++11.
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "3.1.0") 
CMake Error at CMakeLists.txt:35 (find_package):
  By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pangolin",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pangolin" with any
  of the following names:

    PangolinConfig.cmake
    pangolin-config.cmake

  Add the installation prefix of "Pangolin" to CMAKE_PREFIX_PATH or set
  "Pangolin_DIR" to a directory containing one of the above files.  If
  "Pangolin" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

**Comment by stevenlovegrove** [comment]
Did you change the EXPORT_PANGOLIN cmake option? That is required to be on when building the examples or tools.

**Comment by Nurgak** [comment]
Could you please elaborate on this a bit more? I'm having the same issue and I didn't find any documentation on this requirement. A `cmake ..` command in the `build` directory gives me the same error as above.

**Comment by fnoop** [comment]
I've got the same problem when building under puppet.  If I run cmake .. by hand then everything is fine, when run under puppet I get:
```
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns: CMake Error at test/log/CMakeLists.txt:2 (find_package):
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:   By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:   asked CMake to find a package configuration file provided by "Pangolin",
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:   but CMake did not find one.
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:   Could not find a package configuration file provided by "Pangolin"
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:   (requested version 0.4) with any of the following names:
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:     PangolinConfig.cmake
Notice: /Stage[main]/Maverick_vision::Orbslam2/Exec[pangolin-prepbuild]/returns:     pangolin-config.cmake
```
The difference is probably an environment variable somewhere, but it shouldn't be this picky - I'm building dozens of other cmake sources without problem.

**Comment by fnoop** [comment]
@Nurgak It's not a fix, but as a workaround you can skip this bit by passing -DBUILD_TESTS=OFF to cmake

**Comment by Chorior** [comment]
I have the same problem. 

I want to compile orbslam2 for windows, and the orbslam2 project need opencv and pangolin support.
When cmake the orbslam2 , I faced the opencv problem . The output are as follow:

CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


And my solution is selecting the "OpenCV_DIR" to the path where contained the "OpenCVConfig.cmake
  " and "opencv-config.cmake" . Then the problem was solved. ( the path of extracting opencv2.4.9  )


**When I went on cmaking, I got the familiar problem:**

CMake Error at CMakeLists.txt:43 (find_package):
  By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pangolin",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pangolin" with any
  of the following names:

    **PangolinConfig.cmake
    pangolin-config.cmake**

  Add the installation prefix of "Pangolin" to CMAKE_PREFIX_PATH or set
  "Pangolin_DIR" to a directory containing one of the above files.  If
  "Pangolin" provides a separate development package or SDK, be sure it has
  been installed.

But in this time, I do not know how to cmake the pangolin to get the "    PangolinConfig.cmake"
 and   "pangolin-config.cmake". 

I can not change "Pangolin_DIR" to the right path.

Thanks in advance !

**Comment by stevenlovegrove** [comment]
@Nurgak CMake stores package configurations in .cmake/packages, and in your case it looks like it can't write there. Maybe it doesn't have permission

@fnoop if cmake does not export the build dir (as puppet seems to direct it not to), then to use pangolin you should probably install it. That will generate PangolinConfig.cmake file which will either be found automatically if it is on CMake's module path, or you can specify it manually by setting Pangolin_DIR to its parent.

You will have to all trust me that for most users, making use of CMake's export mechanism makes things much simpler (puppet and weird home directory permissions aside). There is something I can do to make it a little more robust in cases where the build-directory is not exported - I will probably get to that at some point.

**Comment by fnoop** [comment]
Aha
https://github.com/intel-iot-devkit/mraa/issues/612

**Comment by fnoop** [comment]
@stevenlovegrove - So my use case in puppet is as an 'exec' resource, effectively calling it from an environment-less shell.  As far as I know it doesn't suppress or restrict anything that happens within the exec, and any shell export within the exec lives for the lifetime of the exec, as far as I can tell (but I'm no expert on the matter).   For compiling projects using cmake exports I normally set CMAKE_PREFIX_PATH explicitly in the exec environment and things go OK.  Maybe if I set this to the compile directory somewhere before starting the compile it might help?

**Comment by hjjayakrishnan** [comment]
I'm also running into the same error while running cmake:
```
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
-- Python Found and Enabled
-- Eigen Found and Enabled
-- V4L Found and Enabled
-- ffmpeg Found and Enabled
-- OpenNI Found and Enabled
-- libuvc Found and Enabled
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at src/CMakeLists.txt:629 (export):
  Cannot create package registry file:

    /home/odroid/.cmake/packages/Pangolin/645635e5c3eb48c40f7fe9ca4be297bf

  No such file or directory



CMake Error at test/log/CMakeLists.txt:2 (find_package):
  By not providing "FindPangolin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pangolin",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pangolin"
  (requested version 0.4) with any of the following names:

    PangolinConfig.cmake
    pangolin-config.cmake

  Add the installation prefix of "Pangolin" to CMAKE_PREFIX_PATH or set
  "Pangolin_DIR" to a directory containing one of the above files.  If
  "Pangolin" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

```@stevenlovegrove Can you please elaborate on the fix you mentioned?

**Comment by stevenlovegrove** [comment]
@hjjayakrishnan it looks like you have some permissions/mount/capacity problem when cmake tries to register Pangolin's build directory within /home/odroid/.cmake/packages/

Since Pangolin isn't registered, it cannot be found (package configuration is missing) when building the examples / tools.

Since the examples and tools are optional, you can turn them off. E.g. by running

`cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..`

This will build the main library which you can then link in your project explicitly (though find_package(Pangolin) will not work).

The real fix would instead be to work out why /home/odroid/.cmake/packages/ cannot be written by cmake.

**Comment by hjjayakrishnan** [comment]
I tried a `sudo cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..`
And I got,
```
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
-- Python Found and Enabled
-- Eigen Found and Enabled
-- V4L Found and Enabled
-- ffmpeg Found and Enabled
-- OpenNI Found and Enabled
-- libuvc Found and Enabled
-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/odroid/Pangolin


```

But still, when I try to do a make after this, I still get `make: *** No targets specified and no makefile found.  Stop.`

**Comment by stevenlovegrove** [comment]
Lets close this issue and track your new problems on the other thread https://github.com/stevenlovegrove/Pangolin/issues/232

**Comment by jwaters10** [comment]
I was trying to build ORB_SLAM2, and was running into the exact same error code as everyone here, but none of the issues listed seemed to be a good fit for me. I realized that I never built Pangolin in the first place, I only partially completed the instructions for the install.

I ran these commands:

git clone https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
mkdir build
cd build
cmake ..
cmake --build .

Then when I tried to build ORB_SLAM2 once more with:

cd ORB_SLAM2
chmod +x build.sh
./build.sh

There was no error message. Definitely a stupid mistake, but I aint the first, hope this helps!

**Comment by rubenanapu** [comment]
Even after compiling `Pangolin` I still had the error.
I solved with:
`export CMAKE_PREFIX_PATH=/path/to/Pangolin/build/src`

In `/path/to/Pangolin/build/src` I had the `PangolinConfig.cmake` file.

**Comment by xavierjs** [comment]
After running:
```
git clone https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin
mkdir build
cd build
cmake ..
cmake --build .
```
I also run:
```
sudo make install
```

and that makes the job. Then I resumed ORB_SLAM2 installation.
