### ISSUE TITLE
What is the Mac camera input?

### ISSUE THREAD

**Issue by bendesign55** [stevenlovegrove/Pangolin#196]
Thanks a lot Steve for making this library! 

I have been trying to make the Mac camera work with the Pangolin for days now. What exact line I have to put for the input name of the Mac built in camera? Is it to do something with ffmpg or the avfoundation?

**Comment by stevenlovegrove** [comment]
I'm afraid Pangolin doesn't have an avfoundation video interface, and I don't know how access the build it camera on a mac. I once tried using libuvc for this but had some trouble because of unusual behaviour from the camera. It's possible that a recent version of libuvc (which is supported by Pangolin) will work. It would be great to hear back from you if you do find a solution that works.

**Comment by stevenlovegrove** [comment]
There has been recent activity on my issue regarding this for the libuvc library. Apparently someone has recently had success using their mac camera with Pangolin:
https://github.com/ktossell/libuvc/issues/1
