### ISSUE TITLE
Cmake error on Windows with VS 2015. Could not find EmbedBinaryFiles

### ISSUE THREAD

**Issue by hari0920** [stevenlovegrove/Pangolin#199]
Hi there, this is my first time posting an issue, sorry if I miss anything.
I'm on Windows 10 with Visual Studio 2015. GLEW did not download and build automatically, so I used the source from (http://glew.sourceforge.net/install.html) and built it using VS. Now I am running into this error with CMake.
If someone could please throw some light on this issue.

CMake Error at CMakeLists.txt:473 (include):
  include could not find load file:

    EmbedBinaryFiles

CMake Error at CMakeLists.txt:476 (embed_binary_files):
  Unknown CMake command "embed_binary_files".

**Comment by stevenlovegrove** [comment]
When GLEW does not download, it's normally because you don't have GIT on your machine for cmake to make use of. Regarding your other problem, I would recommend deleting the Pangolin directory and starting from scratch, as it looks a bit unusual. Is there any chance you have another Pangolin directory somewhere else?

**Comment by hari0920** [comment]
It was a problem with a duplicate directory. Thanks a lot!
