### ISSUE TITLE
Broken build: FFMPEG on Ubuntu 14.04

### ISSUE THREAD

**Issue by ds2268** [stevenlovegrove/Pangolin#209]
Hi,

I am getting the following error concerning installation of Pangolin library:

`ffmpeg.cpp:362:43: error: invalid conversion from ‘const unsigned char*’ to ‘uint8_t* {aka unsigned char*}’ [-fpermissive]
     avpicture_fill((AVPicture*)avsrc, src + src_buffer_offset, fmtsrc, w, h);`

also:

`ffmpeg.cpp:406:13: error: ‘avsrc’ was not declared in this scope
             avsrc = avcodec_alloc_frame();
`

and:

`ffmpeg.cpp:407:13: error: ‘avdst’ was not declared in this scope
             avdst = avcodec_alloc_frame();
`

My system: Ubuntu 14.04

**Comment by Cakem1x** [comment]
I just encountered the same problem. (Also using Ubuntu 14.04, libavutil version 52)
It seems like the latest commit introduced these errors for me.
(see https://github.com/stevenlovegrove/Pangolin/commit/71b223e203b6ae1b4950f47f8738cb18b27d55a9, someone else had the same issue)

Workaround for me was to simply checkout the commit before that one:
git checkout 5f6a60c77c48c8c19bdd5de4c69eeaebe0f7bb0a

**Comment by RansML** [comment]
I have the same issue.

**Comment by lvxingzhe1991** [comment]
where is the address of oder version

**Comment by Cakem1x** [comment]
@lvxingzhe1991 The latest version that still worked for me was 5f6a60c.
You can use this version by checking out this commit in your local repository:
git checkout 5f6a60c

If you're interested in details, take a look at the history of how the code changed:
https://github.com/stevenlovegrove/Pangolin/commits/master
Currently, only one commit happened since the version 5f6a60c. The detailed code changes of that commit can be seen here: https://github.com/stevenlovegrove/Pangolin/commit/71b223e203b6ae1b4950f47f8738cb18b27d55a9

**Comment by RansML** [comment]
@lvxingzhe1991 I just used [ 7987c9b](url)

**Comment by RealRecon** [comment]
Hi everybody,

I'm also affected by this issue (Ubuntu 14.04). Please test whether my PR fixes this for you, too.

Thanks.

**Comment by stevenlovegrove** [comment]
I've just merged in @RealRecon 's fix. Hopefully that will help people out.

**Comment by stevenlovegrove** [comment]
Closing this out. Reopen if someone still hits this problem.
