### ISSUE TITLE
[Install Pangolin] excute command : cmake --build .    (Error like this)

### ISSUE THREAD

**Issue by iDonghq** [stevenlovegrove/Pangolin#268]
error: ‘GL_SHADER_STORAGE_BUFFER’ was not declared in this scope
     GlShaderStorageBuffer = GL_SHADER_STORAGE_BUFFER

**Comment by Coldplayplay** [comment]
I have the same problem. I guess this is the problem of the opengl, but i dont know how to solve it.hope someone can help solve it.

**Comment by iDonghq** [comment]
Maybe not openGL, cause I have tested it; maybe the path of installation or the version of pangolin

**Comment by stevenlovegrove** [comment]
This is probably related to the version of your installed OpenGL, maybe GLEW. You can safely comment that line if you like and the rest should compile fine.

The best solution is probably to find some #define with the OpenGL version to guard against this in the future.

**Comment by glc12125** [comment]
@stevenlovegrove , you are right, I believe it is because of OpenGL version. Checked the documention of OpenGL, (https://www.khronos.org/registry/OpenGL-Refpages/gl4/), found that "The GL_DISPATCH_INDIRECT_BUFFER and GL_SHADER_STORAGE_BUFFER targets are available only if the GL version is 4.3 or greater.". And according to the source code, where the error was thrown:

/usr/local/include/pangolin/gl/gl.h:171:29: error: ‘GL_SHADER_STORAGE_BUFFER’ was not declared in this scope:

#ifndef HAVE_GLES                                                                                                           
GlPixelPackBuffer = GL_PIXEL_PACK_BUFFER,           // PBO's                                                            GlPixelUnpackBuffer = GL_PIXEL_UNPACK_BUFFER,                                                                           GlShaderStorageBuffer = GL_SHADER_STORAGE_BUFFER                                                                    #endif 

This is introduced in this change: https://github.com/stevenlovegrove/Pangolin/commit/e66e2048c57061020243fe27f154e4a79f91b49d#diff-d382887f3e1d2d9afcea169f207a1381

I need to checkout a previous commit in order to compile. If OpenGL 4.3 is a prerequisite, we should force that in the building step. If not, this should be fixed.

**Comment by caselitz** [comment]
In my case this problem occurred because I had `${CUDA_TOOLKIT_ROOT_DIR}/samples/common/inc` in my cmake `include_directories` (to `#include <helper_cuda.h>).`

As there exists a directory `GL`, I suspect this causes `pangolin/gl/glplatform.h` to include the wrong `<GL/gl.h>`. At least removing this path from the `include_directories` solved the problem for me.

**Comment by popsheng** [comment]
`@caselitz I meet the same problem. just change `<GL/glew.h>` in `pangolin/gl/glplatform.h` using `/usr/include/GL/glew.h` works.
