### ISSUE TITLE
Wrong pitch size in Transform() in image.h

### ISSUE THREAD

**Issue by pinglin** [stevenlovegrove/Pangolin#269]
Hi Steve, 

I came across using `Fill` in `image.h` and found the pitch size is probably wrong:
https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/image/image.h#L137

Or, is the `w` expected to be there?  Thanks for checking this in advance.

Pinglin

**Comment by stevenlovegrove** [comment]
It looks correct to me - the end iterator is w (width) elements after the start of the row. It assumes the type T of the image is correct.

**Comment by pinglin** [comment]
The unexpected manner happens with `TypedImage` initiated with `fmt.bpp == 24` for 3-channel images in this [line](https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/image/typed_image.h#L45). This will cause `w` and `pitch` inconsistent. I expected that `Fill` is supposed to fill in value at entire allocated image memory. 

The current [code](https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/image/image.h#L137) will traverse only one third of image row. Or do I misunderstand the purpose of `Fill` and `Transform`?

**Comment by stevenlovegrove** [comment]
The issue is that the Image class is templated and is returned with a
default type of unsigned char, which I appreciate is confusing.

Fill and transform operate on the image type, which in this case should be
first unsafe_reinterpret()'d to some uchar3 type of your choice.

Images may be interlaced or have padding, so operating on all the bytes
allocated is not the right thing to do.

A cleaner solution may be to return some variant type, but that is for the
future.

**Comment by pinglin** [comment]
Got it. I think `UnsafeReinterpret` can be the workaround for me now. Thanks.
