### ISSUE TITLE
Forwarding input from Handler to my BaseApplication

### ISSUE THREAD

**Issue by JmanVtrus** [stevenlovegrove/Pangolin#276]
Greetings all,

I am trying to find an example of forwarding keyboard and mouse input from Pangolin to my own class... I see there is a RegisterKeyPressCallback but little for mouse events. I am hoping to find a way to that does so without subclassing Handler3D and . Perhaps eEven better if there is a general Event system,  Ie:  MouseDragEvent : BaseEvent,  and KeyPressEvent: BaseEvent,  WindowResizedEvent,  passed to me via an   OnEvent(  BaseEvent ).  My application initializes and uses pangolin via the following steps:

1. pangolin::CreateWindowAndBind
2. pangolin::OpenGlRenderState && pangolin::Handler3D
3.  pangolin::CreatePanel && pangolin::CreateDisplay
4. Runs GameLoop / MessagePump

Or perhaps this approach is better served an alternative way, the end result I am trying to achieve:
1. Abstract window event management from my Application class over polling style.
2. Create a standard FPS controller by modifying the renderStates matrices
3. Process things like a double click to zoom in via a camera raycast to SceneObject/Actor/Entity

**Comment by stevenlovegrove** [comment]
The current mechanism for doing this is exactly by implementing the Handler interface (doesn't need to be Handler3D). If you were to set the handler for the pangolin::DisplayBase() view, that would effectively be global since events are hierarchically dispatched through the layout tree.

A scenegraph style mechanism does actually exist in Pangolin (though it is not very mature) in the 'pangolin/include/scene' directory. SceneHandler (https://github.com/stevenlovegrove/Pangolin/blob/master/include/pangolin/scene/scenehandler.h) is a subclass of Handler3D that deals with mouse rays intersecting a scene graph for manipulation, etc. Double click to zoom and FPS style navigation could easily be implemented in a Handler3D sub-class.

Is there a reason you don't want to implement the Handler interface?

**Comment by JmanVtrus** [comment]
Ah! Thanks very much for the example, it makes sense and I realized I just misinterpreted the header file. I get to used to naming things virtual OnEvent for so many years I overlooked the base IHandler class.
