### ISSUE TITLE
cmake --build . 

### ISSUE THREAD

**Issue by naonaomxy** [stevenlovegrove/Pangolin#294]
when I did this step 'cmke --build .',some errors occurred. How to solve it? Thank you very much.

/usr/bin/ld: /usr/local/lib/libavcodec.a(avpacket.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavcodec.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/pangolin.dir/build.make:2009: recipe for target 'src/libpangolin.so' failed
make[2]: *** [src/libpangolin.so] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevenlovegrove** [comment]
I don't know. This seems unusual. Any exotic build target or toolchains lying around?

**Comment by jprodriguezg** [comment]
I had a similar issue by installing Pangolin. The problem was given by the previous installation of ffmpeg (It uses libavcodec.a). Basically, I didn't enable the option for compiling with shared libraries.

If it's your case, you can solve the issue by recompiling ffmpeg. First, you need to clean the tree in the ffmpeg project by using `make clean`. Then, you reconfigure by adding the following commands: `./configure --enable-shared --extra-ldexeflags=-pie --extra-cflags=-fPIC --extra-cflags=-m64`. Finally, you compile ffmpeg again. 
Once I recompiled, I built again Pangolin without any issue.

Hope it helps you

**Comment by andylei77** [comment]
A guide for Compiling FFmpeg on Ubuntu 16.04 https://gist.github.com/teocci/f7a438013a0197a91446ee86de41faee

**Comment by zheweijushi** [comment]
> I had a similar issue by installing Pangolin. The problem was given by the previous installation of ffmpeg (It uses libavcodec.a). Basically, I didn't enable the option for compiling with shared libraries.
> 
> If it's your case, you can solve the issue by recompiling ffmpeg. First, you need to clean the tree in the ffmpeg project by using `make clean`. Then, you reconfigure by adding the following commands: `./configure --enable-shared --extra-ldexeflags=-pie --extra-cflags=-fPIC --extra-cflags=-m64`. Finally, you compile ffmpeg again. Once I recompiled, I built again Pangolin without any issue.
> 
> Hope it helps

it works. thank you very much
