### ISSUE TITLE
auto-resize

### ISSUE THREAD

**Issue by phil0stine** [stevenlovegrove/Pangolin#316]
From [Resize function](https://github.com/stevenlovegrove/Pangolin/blob/0b0220c3bb219409c890838adec95830b73b7619/include/pangolin/display/display.h#L148) :

>    /// Tell pangolin base window size has changed
>    /// You will need to call this manually if you haven't let
>    /// Pangolin register callbacks from your windowing system  

Simple question, how to achieve this. I am using X11, and as far as I can tell, all other callbacks such as MouseMotion are being passed up to the `Handler3D`, however when I resize the X11 window, then try to zoom in on the scene, nothing is rendered in the new space created by resizing the window.

**Comment by stevenlovegrove** [comment]
You are in full control of the render loop. The FinishFrame() call is going to swap the front/back buffers and process events (mouse/keyboard/window/etc). If it that space is not redrawn it may be because you are not issuing any draw calls over that region (perhaps because you are using a view with fixed aspect ratio or bounds), or perhaps if you have enabled a scissor area or something. I would expect the Pangolin samples do not have the issue you describe because they are clearing the frame buffer (both colour and depth) each loop.

**Comment by phil0stine** [comment]
> You are in full control of the render loop.

Exactly why I was surprised to find the rendering got cut off after resizing. Nothing fancy in my rendering, I have no scissor area, and I am also clearing both the buffers each loop. I will look more into the fixed aspect ratio as a possibility, thanks.

**Comment by stevenlovegrove** [comment]
Are you seeing junk, or just black? If it is the latter, then you should look at the HelloPangolin example. There you can see a strange negative(!) aspect ratio. It is completely unintuitive, but that causes it to overdraw the View and will have the effect that you want, probably. You could also disable the aspect ratio entirely, but that will cause some stretching unless you modify the ProjectionMatrix appropriately.

**Comment by phil0stine** [comment]
It turned out to be my use of FBOs, I am simply blitting a color attachment to the default buffer (and nothing else), for which I did not take into account the new destination size. I still don't have it quite working but that was the root of the problem.
