### ISSUE TITLE
Issues When Trying ORB_SLAM2 Examples

### ISSUE THREAD

**Issue by kuangjies** [stevenlovegrove/Pangolin#384]
I finished building ORB_SLAM2 without any trouble. But when I started to try different given examples I met the same problem:

terminate called after throwing an instance of 'pangolin::WindowExceptionNoKnownHandler'
what(): No known window handler for URI 'linux'
Aborted (core dumped)

Any ideas? Thanks.

**Comment by stevenlovegrove** [comment]
Sorry you never got a reply on this. Likely the X11 driver didn't get built because it couldn't find the required dependency. For anyone else seeing this, check that your preferred windowing system library is detected during the cmake configure stage. E.g. for X11 https://github.com/stevenlovegrove/Pangolin/blob/7cb7c2e35425b2cdaf0480a1bc0c74b8f4d6ab77/components/pango_windowing/CMakeLists.txt#L27 should succeed.
