### ISSUE TITLE
About the OpenGL version on Mac OS

### ISSUE THREAD

**Issue by ihpdep** [stevenlovegrove/Pangolin#470]
Hi there, I am trying to play pangolin with OpenGL 4.1 on Mac OS. I can use OpenGL 4.1 in Xcode with GLFW and I can run pangolin example with Xcode but only in OpenGL 2.2. I want to ask is there any way to specify the version OpenGL? Or maybe any way to use GLFW window in pangolin since GLFW uses OpenGL 4.1? Thanks

**Comment by stevenlovegrove** [comment]
I believe https://github.com/stevenlovegrove/Pangolin/blob/master/src/display/device/display_osx.mm#L142 is where the profile is selected. If I remember correctly, I had to use legacy to remain backwards compatible - we should probably make that an argument so that people can override it - happy to take a PR there if you make that work.

There is also an open PR which adds GLFW support https://github.com/stevenlovegrove/Pangolin/pull/394, but it hasn't made it upstream yet.

**Comment by ihpdep** [comment]
Thanks for your reply. I changed profile in display_osx.mm and the pangolin SimpleDispalyImage example fails to run. It keeps printing "OpenGL Error: XX (502)" in the cmd and the window is blank. The error line is in GlTexture::Upload(). Also, for the HelloPangolin example, there is no error message and the window is blank. 

The version of OpenGL is changed into 4.1 successfully. Does Pangolin support OpenGL > 3.X? I searched a little bit. It seems there is difference between using 2.X and 3.X in development.

I am in the middle of my project and suddenly find that I need some features in >3.3. Do you have any advice for using 3.3 in Pangolin? Really don't want to start the project again. >_<

**Comment by stevenlovegrove** [comment]
With OpenGL 4.1 there is no fixed pipeline and so every render operation requires a user defined shader if I remember correctly - Most of Pangolin's examples will not work in this case (SimplePlot may be the one exception) but it does not stop you from using Pangolin to create the context, manage viewports and use it's handler mechanism. The difference is that you will need to define a vertex and fragment shader and upload the modelview matrix as a uniform.

I'm afraid I do not have any minimal examples of this, but the ModelViewer application in Pangolin/tools does something similar using Pangolins GlSlProgram utility class.
