### ISSUE TITLE
Make error in Ubuntu 14.04

### ISSUE THREAD

**Issue by 95ImadEL** [stevenlovegrove/Pangolin#555]
Hello everyone.

I tried to build the Pangolin in Ubuntu 14.04, but it failed. I have a make error, it produced the following error:

```
imad@nguyen-arria5:~/Desktop/ORB2_SLAM/Pangolin/build$ sudo cmake --build .
[  1%] Generating xdg-shell-client-protocol.h
usage: ./scanner [client-header|server-header|code]

Converts XML protocol descriptions supplied on stdin to client headers,
server headers, or protocol marshalling code.
make[2]: *** [src/xdg-shell-client-protocol.h] Error 1
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
make: *** [all] Error 2
```
thank you in advance for your collaboration

**Comment by christian-rauch** [comment]
This error is related to Wayland. I haven't tested this on Ubuntu 14.04 since it is EOL.
Can you reproduce this on Ubuntu 16.04 or 18.04?

Alternatively, you can manually disable the Wayland build via `cmake -DDISPLAY_WAYLAND=0 ..`. However, I would recommend updating your Ubuntu to a newer version.

**Comment by 95ImadEL** [comment]
Thank you so much @christian-rauch, it works very well on Ubuntu 18.04

**Comment by christian-rauch** [comment]
@OldAAAA Can you be more specific about what doesn't work and what you mean with "upgrade system operation"?

**Comment by OldAAAA** [comment]
Thank you for reply!Here is the detail issue:
when i input "cmake --build ."There are some error display in terminal.

> usage: ./scanner [client-header|server-header|code]
> Converts XML protocol descriptions supplied on stdin to client headers,
> server headers, or protocol marshalling code.
> make[2]: *** [src/xdg-shell-client-protocol.h] Error 1
> make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2

and then i see this issue in github,so i remove the build directory,and do "cmake -DDISPLAY_WAYLAND=0 ..",and then do "cmake --build .".But the same error as before displays in the terminal

"the upgrade system operation" means i can't upgrade my system to ubuntu 16.04 or 18.04,because there are many other projects rely on ubuntu 14.04.

**Comment by christian-rauch** [comment]
Primarily, I recommend switching to an Ubuntu LTS version that is still supported by Canonical. Since other projects stopped supporting older Ubuntu versions, you will probably hit other issues along your way.

Your issue is related to the fact that CMake assumes that the `wayland` libraries were found, but the `wayland-scanner` is not installed. I am unable to reproduce this issue on a virtual machine with Ubuntu 14.04.

In the default setup with no wayland installed, the cmake variable `WAYLAND_CLIENT_FOUND` should be `FALSE`. In this case `cmake ..` (version 2.8.12.2) should report something like:
```
-- Could NOT find WAYLAND_CLIENT (missing:  WAYLAND_CLIENT_LIBRARIES WAYLAND_CLIENT_INCLUDE_DIR) 
-- Could NOT find WAYLAND_SERVER (missing:  WAYLAND_SERVER_LIBRARIES WAYLAND_SERVER_INCLUDE_DIR) 
-- Could NOT find WAYLAND_EGL (missing:  WAYLAND_EGL_LIBRARIES WAYLAND_EGL_INCLUDE_DIR) 
-- Could NOT find WAYLAND_CURSOR (missing:  WAYLAND_CURSOR_LIBRARIES WAYLAND_CURSOR_INCLUDE_DIR) 
-- Could NOT find WAYLAND (missing:  WAYLAND_LIBRARIES WAYLAND_INCLUDE_DIR) 
```

Maybe you have a mix of installed and not-insalled wayland packages.
You can either try to install wayland as described in the README via: `sudo apt install pkg-config libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols` or remove every package that is related to wayland.

If nothing helps, a dirty workaround is to just remove the parts from the `src/CMakeLists.txt`.
