### ISSUE TITLE
How to build with Eigen on Windows?

### ISSUE THREAD

**Issue by omgitsraven** [stevenlovegrove/Pangolin#574]
I'm trying to build https://github.com/mp3guy/ElasticFusion on Windows, which it says depends on Pangolin being built with dependencies on OPENNI2 and EIGEN3.

Well, when I configure Pangolin in Cmake-gui, the log mentions `OpenNI2 Found and Enabled`, but I can't find anything in the log or in the values that mentions Eigen, so I don't know how to tell it where Eigen is installed—and if I don't mention it at all, when I eventually get to the point of building ElasticFusion, I get errors like `Cannot open include file: 'Eigen/Dense': No such file or directory`.

Based on https://github.com/stevenlovegrove/Pangolin/issues/355 , I tried adding a CMake value `EIGEN_INCLUDE_DIR` that pointed to my copy of Eigen, but that didn't help, and neither did naming the value `EIGEN3` as the ElasticFusion readme seemed to be implying... Neither did trying both those names as environment variables pointing to it.

What is the intended way to "compile Pangolin with Eigen"? Many issues on the ElasticFusion repo mention it as the solution to the issue, but none of them clarify how to do so, and I can't really find any discussion of it anywhere else, other than the Pangolin readme mentioning it as a "very optional dependency" with no clarification of how to integrate it when one wants to, and the aforementioned https://github.com/stevenlovegrove/Pangolin/issues/355 which is a bit over my head and might not actually be the same issue at all? (I've also asked this on the ElasticFusion repo, but I thought I'd check if it's a problem that would be familiar to people building Pangolin in general...)

**Comment by Wjiajie** [comment]
Have you worked it out? I got the same issue.

**Comment by omgitsraven** [comment]
Still totally stumped on it; haven't gotten any replies yet here or there ( https://github.com/mp3guy/ElasticFusion/issues/196 )

I'm wondering if it might have something to do with using an older version of either Pangolin or Eigen (given that the instructions I'm following are a few years old) but I'm far enough out of my element that I'm not even sure where to start figuring it out, sadly…

**Comment by timhutton** [comment]
Pangolin comes with its own FindEigen.cmake in CMakeModules, that seems to work a bit differently to the one included with CMake.

I had to set ```EIGEN_INCLUDE_DIR``` to the location of the unzipped Eigen source (in my case ```H:/Eigen/eigen-3.3.7```).

Doing that causes the magic line ```Eigen Found and Enabled``` to appear in the CMake output when configuring, without which Eigen won't be available.

**Comment by stevenlovegrove** [comment]
If this doesn't work for your configuration, you might want to look at https://github.com/stevenlovegrove/Pangolin/blob/master/CMakeModules/FindEigen.cmake

This is the logic CMake is using to attempt to find Eigen on your system. Notably you can communicate with this CMakeModule using the 'EIGEN_INCLUDE_DIR' variable as a hint. You can see from the script that it is looking to find ${EIGEN_INCLUDE_DIR}/Eigen/src/Core/util/Macros.h so you should make sure the EIGEN_INCLUDE_DIR hint you're providing points to a valid file when substituted into that expression.

My guess is that you're providing the wrong base directory, such as 'H:/Eigen/eigen-3.3.7/Eigen' instead of 'H:/Eigen/eigen-3.3.7' as @timhutton advised above, which is easily done!

**Comment by omgitsraven** [comment]
OK, digging through the CMakeModule revealed the problem: it's `EIGEN3_INCLUDE_DIR`, not `EIGEN_INCLUDE_DIR`! Not sure when that changed, but, giving it that way results in the "Eigen Found and Enabled" line. Thanks!
