### ISSUE TITLE
I don't find the tutorial and example for the transformation and how to use translate and rotation Matrix

### ISSUE THREAD

**Issue by BillZHOU110** [stevenlovegrove/Pangolin#591]
Hello, first of all, I am new for this software and I haven't learnt Opengl. But I want to know how to use this software to help me to make a program for visulisation on C++. However, I can't find tutorial and example for the transformation and how to use translate and rotation Matrix. Ainsi, I hope you can add some examples for it and sincerely add an example to visulize un trojectory by use the data set. Thank you.

**Comment by stevenlovegrove** [comment]
Thanks for this suggestion. I generally recommend that people familiarize themselves with OpenGL before trying to use Pangolin because it is only a light wrapper. I would recommend a reference such as http://www.songho.ca/opengl/gl_transform.html to learn about the OpenGL transforms and how to use them. I will add a link to this resource in the readme for future users.
