### ISSUE TITLE
Does Pangolin support 3d picking?

### ISSUE THREAD

**Issue by zhangjun-xyz** [stevenlovegrove/Pangolin#596]
During debugging, it's really handy to show more infos about the object under cursor. So I wonder whether Pangolin support picking?

**Comment by stevenlovegrove** [comment]
It has some very limited support but it isn't very mature or extensive. There is a small SimpleScene example which uses the SceneGraph which is the basis for picking in pangolin. There is a PR https://github.com/stevenlovegrove/Pangolin/pull/628 which talks about it a bit. I don't advertise this feature much because the API is a bit experimental.
