### ISSUE TITLE
Flashing issue.

### ISSUE THREAD

**Issue by dwindy** [stevenlovegrove/Pangolin#604]
Hi, Does anyone know why the screen keep flashing?
I am new with Pangolin.
Tried to draw a trajectory but the window keeps flashing.
I have run the example, there is no such issue.
Thanks ~~~
finger crossed.

Below is the code I used:
![flash](https://user-images.githubusercontent.com/11047587/83643011-73d9da80-a5a7-11ea-8797-1d062b98b403.png)

**Comment by xvzezi** [comment]
Sorry to bother,
but have you fixed this problem?

**Comment by xvzezi** [comment]
Maybe Flickering issue is a more concrete description.
After testing, on my Ubuntu 16.10 LTS desktop PC, using original gl* drawing functions will lead to this happening.
for example, glDraw() -> glEnd(), then the output frames will flicker. And when i draw with only a line, the PC is stuck and seems to fall in a infinite loop(when comment usleep line).
However, using pangolin::gl* drawing functions seem to be working well. And no need to call usleep to maintain good response.
SO in this case, one can use pangolin::glDrawLine to avoid flickering issue.

BUT, ORB_SLAM2 is using gl* drawing functions without any problems. To be ensure what had happened because of no warning or error logs.

**Comment by wwtinwhu** [comment]
> Maybe Flickering issue is a more concrete description.
> After testing, on my Ubuntu 16.10 LTS desktop PC, using original gl* drawing functions will lead to this happening.
> for example, glDraw() -> glEnd(), then the output frames will flicker. And when i draw with only a line, the PC is stuck and seems to fall in a infinite loop(when comment usleep line).
> However, using pangolin::gl* drawing functions seem to be working well. And no need to call usleep to maintain good response.
> SO in this case, one can use pangolin::glDrawLine to avoid flickering issue.
> 
> BUT, ORB_SLAM2 is using gl* drawing functions without any problems. To be ensure what had happened because of no warning or error logs.

Thanks. pangolin::glDrawLine can avoid flickering issue indeed!  I am also wondering what's wrong with gl functions. Hope someone can find the reason.

**Comment by tiemuhua** [comment]
深蓝学院的课？解决了没

**Comment by dwindy** [comment]
> 深蓝学院的课？解决了没

装个显卡驱动好了

**Comment by dwindy** [comment]
> Sorry to bother,
> but have you fixed this problem?

well, It was solved by simply installing the Graphic Driver.
