### ISSUE TITLE
How to solve this error

### ISSUE THREAD

**Issue by MSathishkumar1990** [stevenlovegrove/Pangolin#610]
(base) dinesh@dinesh-MS-7B24:~/Pangolin/build$ cmake ..
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenGL.cmake:369 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:169 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dinesh/Pangolin/build/CMakeFiles/CMakeOutput.log".

**Comment by somepablo** [comment]
In my case that problem was caused because libGL.so and libEGL.so was not existing inside "/usr/lib/x86_64-linux-gnu/".

Just created 2 symlinks and it worked:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so
sudo ln -s /usr/lib/x86_64-linux-gnu/libEGL.so.1 /usr/lib/x86_64-linux-gnu/libEGL.so`

**Comment by stevenlovegrove** [comment]
libGL.so is often provided by your graphics card driver (e.g. NVidia drivers). You can make sure they are installed correctly and accessible (e.g. somepablo's symlink) or install a software rasterizer on Linux like the mesa drivers.

**Comment by Achint08** [comment]
I followed this on Ubuntu 18.04 and it worked:
https://www.cyberciti.biz/faq/ubuntu-linux-install-nvidia-driver-latest-proprietary-driver/

Thanks @stevenlovegrove
