### ISSUE TITLE
compile error in handler.cpp

### ISSUE THREAD

**Issue by wendouzi** [stevenlovegrove/Pangolin#665]
![image](https://user-images.githubusercontent.com/6001667/130172999-a04b9db1-5583-4a4a-800f-695bf14f61f5.png)

As picture shows

**Comment by stevenlovegrove** [comment]
I just checked on the master branch and this has already been fixed https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/src/handler.cpp#L136

If you're using GLES you might be interested in that branch because the GLES codepath is getting built for emscripten (github.com/stevenlovegrove/Pangolin/runs/3561611501).
