### ISSUE TITLE
Cannot install plain vanila version on Debian Buster

### ISSUE THREAD

**Issue by zsoltszakaly** [stevenlovegrove/Pangolin#674]
I followed step-by-step the installation as in REAME.md with no extra step.
Up to 
`cmake ..`
it worked, although
`./scripts/install_prerequisites recommended`
should be 
`./scripts/install_prerequisites.sh recommended`
It needed the root password but then it found all dependencies already installed.

Then at cmake I got
```
CMake Warning at CMakeLists.txt:75 (message):
  Building Tests requested, but Catch2 library not found.


-- libpng Found and Enabled
-- libjpeg Found and Enabled
-- libtiff Found and Enabled
-- libopenexr Found and Enabled
-- liblz4 Found and Enabled
-- libzstd Found and Enabled
-- pybind11 v2.7.1 
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "<string>", line 9, in wheel_name
  File "/usr/lib/python3.7/distutils/dist.py", line 857, in get_command_obj
    klass = self.get_command_class(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 848, in get_command_class
    return _Distribution.get_command_class(self, command)
  File "/usr/lib/python3.7/distutils/dist.py", line 843, in get_command_class
    raise DistutilsModuleError("invalid command '%s'" % command)
distutils.errors.DistutilsModuleError: invalid command 'bdist_wheel'
CMake Error at cmake/MakePythonWheel.cmake:31 (list):
  list GET given empty list
Call Stack (most recent call first):
  components/pango_python/CMakeLists.txt:71 (MakeWheel)
  CMakeLists.txt:93 (include)


-- libdc1394 Found and Enabled
-- V4L Found and Enabled
-- ffmpeg Found and Enabled
-- OpenNI Found and Enabled
-- OpenNI2 Found and Enabled
-- Configuring incomplete, errors occurred!
See also "/home/x/Pangolin/build/CMakeFiles/CMakeOutput.log".
See also "/home/x/Pangolin/build/CMakeFiles/CMakeError.log".
```
The first surprise is the "Building Tests requested". It was not requested and the default should be Release. I even tried `-DCMAKE_BUILD_TYPE=Release`
but no change. Anyway, I think it changes back to Release when Catch2 is not found.

The real problem is that I got the 
`-- Configuring incomplete, errors occurred!`
I tried to read the long CMakeOutput.log, but no obvious error I found.
In the CMakeError.log the first error is
```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/x/Pangolin/build/CMakeFiles/CMakeTmp
```
although the directory exists. Later it complains about undefined reference to pthread_create and ld not finding -lpthreads, but according to some SO questions it is a known CMake bug that at the end it complains about lpthreads even if the error is earlier.
Any help? Thanks,

**Comment by stevenlovegrove** [comment]
Thanks for reporting. The error you're showing is because the method I'm using to determine the correct python install wheel name uses bdist_wheel which apparently doesn't work on your platform.

The recommended workaround depends on whether you need python or not. If you don't need it, the best thing to do is disable the python build component. I'm not at a computer right now to check, but there should be an option like BUILD_PYTHON in cmake or you can explicitly set one of the python variables to "".

If you do need python, you can either try to debug the wheel filename generation logic (at the line cmake line shown in the error), or simply comment out the entire method if you know how to install the generated pypangolin.so manually for your distribution.

Finally, you can also move to a stable release tag if you prefer.

**Comment by zsoltszakaly** [comment]
Thank you. I downloaded the latest release and it works.

**Comment by stevenlovegrove** [comment]
This is related to #683 and a warning / workaround is in 57b862be24e13baa7f479dce46f0a8dba1ffe1e2
