### ISSUE TITLE
Old compiler not C++17 compliant

### ISSUE THREAD

**Issue by HU-517** [stevenlovegrove/Pangolin#676]
make[1]: *** [CMakeFiles/pango_vars.dir/all] Error 2
/home/hu/Software/Pangolin-master/components/pango_windowing/src/display_x11.cpp: In member function 'virtual void pangolin::X11Window::ProcessEvents():
/home/hu/Software/Pangolin-master/components/pango_windowing/src/display_x11.cpp:403:13: error: no matching  function for call  to
'pangolin::MouseEvent::MouseEvent(<brace-
enclosed initializer list>)'
            }));
             ^

**Comment by stevenlovegrove** [comment]
Can you please give the full build output and say what platform you're on?

**Comment by ssaye** [comment]
I have met the same problem, and my platform is Ubuntu16.04 on VMware，the build output are shown below:

![image](https://user-images.githubusercontent.com/5242468/133732826-4a723087-c4b8-40a6-9647-9e42c2bcaac1.png)

**Comment by stevenlovegrove** [comment]
Thanks for the info @ssaye. If you're on 16.04 (from 2016) I guess you're probably also on an old compiler.

I committed 914b5ef46bd409738f36045a00305bc514c4de49 in the hopes that it may help. Otherwise I'd recommend upgrading your compiler or fiddling with the syntax on those lines. Basically, it doesn't like the initialization of the subclass including the base-class fields but that is valid C++. Let me know if it works or if you find a code workaround that I can commit. I'll close for now.

**Comment by DandyLorenz** [comment]
I made the same mistake.I am run ROS ubuntu 16.04 kinetic,I installed eigen3 3.3.7 and opencv 2.4.9.1。I am do this code：
`cd ~/your_fav_code_directory
git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
cd Pangolin 

# Install dependencies (as described above, or your preferred method)
./scripts/install_prerequisites.sh recommended

# Configure and build
mkdir build && cd build
cmake ..
cmake --build .`
it‘s build error，please help me
![image](https://user-images.githubusercontent.com/40449226/141050174-047164a4-854f-4f03-8e44-5058e0e47f64.png)
