### ISSUE TITLE
Does this still work with an Oculus (CV1) headset?  Any pointers to making it work?

### ISSUE THREAD

**Issue by Fredrum** [stevenlovegrove/Pangolin#699]
Hello!
I have gotten a bit further in my experimental program and I'd now love to see how it looks through my Oculus CV1 headset.
Iv'e got a Original Vive too if that's supported.

So before I spend countless hours trying to get that up and running I just wanted to check if anyone knew if the Pangolin Oculus support is still working?
Is it using OpenXR?

Cheers!

**Comment by stevenlovegrove** [comment]
Hi @Fredrum - I'm afraid the original Oculus support was for the DK2 some time ago, and that has since been removed. If you wish to incorporate with the current Oculus SDK or OpenXR, the main piece of work is populating https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_opengl/include/pangolin/gl/opengl_render_state.h#L216 the `projection` and `modelview_premult` matrices for each view from the SDK, and rendering the scene twice for each eye. A general Pangolin application needs code changes to render twice, so you will need to understand what you're doing.

Best

**Comment by Fredrum** [comment]
Thank you that's very helpful!
It sounds like the best thing in my case would be to lift my experiments over to another software that already has some working HMD support. Maybe Godot or Unreal or something.
Thanks!
