### ISSUE TITLE
Generating xdg-shell-client-protocol.h  error

### ISSUE THREAD

**Issue by ming5432ming** [stevenlovegrove/Pangolin#714]
hi, i Build it on ubuntu16.  but i meet an error as follows:

![image](https://user-images.githubusercontent.com/25290190/143420674-24d5172e-d27b-4ea6-a557-ac7517e09ee1.png)

![image](https://user-images.githubusercontent.com/25290190/143421019-3c4db2e1-afa7-4ee6-9291-a917336f9916.png)

i dont know how to solve it . could u help me
thank you

**Comment by koko-tan** [comment]
same error :(

**Comment by koko-tan** [comment]
Same error :(

**Comment by koko-tan** [comment]
Same error on ubuntu18.04.
![image](https://user-images.githubusercontent.com/25245414/143516297-d486e10a-d269-45f7-85fe-97fbccd9b818.png)

**Comment by koko-tan** [comment]
./scripts/install_prerequisites.sh

See in README.

**Comment by ming5432ming** [comment]
> ./scripts/install_prerequisites.sh
> 
> See in README.

i have already run './scripts/install_prerequisites.sh recommended'.    

you solver the problem  after  run './scripts/install_prerequisites.sh recommended'.  ?

**Comment by inventionzhang** [comment]
I meet the same problem and run './scripts/install_prerequisites.sh recommended'.  But haven't solved it. @koko-tan

**Comment by inventionzhang** [comment]
well， I switch to branch v0.6 and do not meet that problem.

**Comment by stevenlovegrove** [comment]
I would guess there is something missing in the wayland install, as required [here ](https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_windowing/CMakeLists.txt#L57)

If I were you, i'd try checking the ${WAYLAND_SCANNER} and ${WAYLAND_PROTOCOLS_DIR} cmake variables that gets set by adding the following on line 52:

```
message(STATUS "WAYLAND_PROTOCOLS_DIR: ${WAYLAND_PROTOCOLS_DIR}")
message(STATUS "WAYLAND_SCANNER: ${WAYLAND_SCANNER}")
```

If either are empty then something went wrong finding wayland. If they are set, then check that '${WAYLAND_PROTOCOLS_DIR}/stable/xdg-shell/xdg-shell.xml' exists.

@christian-rauch In case he has any ideas.

**Comment by christian-rauch** [comment]
On Ubuntu 16.04, the package `wayland-protocols` does not contain the `xdg-shell/xdg-shell.xml`. I used to have a fallback for when that protocol definition is not available. But since Ubuntu 16.04 went EOL in April, I simplified the CMake file and removed that fallback.

@ming5432ming I strongly recommend that you switch to an Ubuntu version that is still supported (18.04, 20.04). You may encounter other supporting issues with an old Ubuntu version. If you have to stay on Ubuntu 16.04, you should remove all Wayland development packages so that the CMake script skips the `WaylandWindow` factory.

**Comment by christian-rauch** [comment]
@ming5432ming In stead of posting screenshots of the terminal, it is better to copy & paste the raw text. Then it is easier to read and it will also be easier to do a full-text search in the issue database.

**Comment by christian-rauch** [comment]
@ming5432ming Can you check if my PR https://github.com/stevenlovegrove/Pangolin/pull/715 solves your issue?

**Comment by zhyx490991014** [comment]
Meet the same problem with Ubuntu18.04... master branch

**Comment by AkerIII** [comment]
Me too, Ubuntu18.04

**Comment by christian-rauch** [comment]
@zhyx490991014 @AkerIII Does the proposed fix in PR #715 solve your issue?

**Comment by yashsoni501** [comment]
@christian-rauch I had the same issue in Ubuntu 18.04. The above PR resolved it. Thanks

**Comment by Hothin** [comment]
> 



> @ming5432ming你能检查我的PR #715是否能解决你的问题吗？

Meet the same problem with Ubuntu18.04. And after I try above PR 715,I meet a new problem.
as follows: 
CMake Error in components/pango_windowing/CMakeLists.txt:
  A logical block opening on the line

    /home/khothin/Pangolin/components/pango_windowing/CMakeLists.txt:3 (if)

  is not closed.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)
could u help me to solve this problem?thank u very much

**Comment by christian-rauch** [comment]
> I meet a new problem

This seems to be an unrelated issue. What CMake version are you using? The block that starts at line 3 ends at line 75.  No idea why this is not parsed correctly. Please check that you correctly applied my patch or switched to the branch without merge issues.

Can you test if this issue also appears if you install all the required wayland packages instead of using the PR?
