### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by smileyenot983** [stevenlovegrove/Pangolin#747]
Hello everyone, 

After building as it is described in readme i got this error:

./HelloPangolin: error while loading shared libraries: libpango_core.so: cannot open shared object file: No such file or directory
 
I have this error after i write cmake and make when i try to run the executable

**Comment by stevenlovegrove** [comment]
I'm not sure why this would happen - did you move any files around? As it says, the .so isn't where it is expecting it to me, so you presumably have some rpath issue. Try reading this page: https://amir.rachum.com/blog/2016/09/17/shared-libraries/#rpath-and-runpath

**Comment by Mr-brillianter** [comment]
I am having the same problem when I was compiling ORB_SLAM. I think it is due to my deleting files that begin with libpango by mistake,when I was trying to remove pangolin latest version manually. I confused pango with pangolin. I assumed the file was DDL of pango library.  Now I found nowhere to get these files, where should I go for them? Any Suggestion ?

**Comment by christian-rauch** [comment]
If you moved files around, maybe it's best to just do a clean build from the start and leave the installed files where they are.

**Comment by hongdayu** [comment]
ldconfig

**Comment by christian-rauch** [comment]
> ldconfig

This only works if the library in question is in one of the search paths. This will not be the case for custom build spaces.

**Comment by farhad-dalirani** [comment]
I faced the same problem, I used ` sudo ldconfig`, and the problem was solved. 
Also if followed this installation guide: https://gitlab.ethz.ch/3dv/pangolin
