### ISSUE TITLE
CMake Error: Error: generator : Ninja Does not match the generator used previously: Unix Makefiles Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

### ISSUE THREAD

**Issue by Xuanhoang214** [stevenlovegrove/Pangolin#775]

**Comment by Aharonez** [comment]
hey did you solve it?

**Comment by stevenlovegrove** [comment]
For context, in case you're confused, Ninja is an alternative to the traditional make. This error means you (or a tool you're using, such as VSCode / QtCreator) has initialized a build directory with make, and you're trying (or a tool you're using is trying) to use Ninja. When Ninja is detected on a system, some IDE's can be a bit gun-ho in trying to use it.

It might not matter - you could just use the other tool. I.e. type make instead of ninja, etc.

If you do want to use Ninja, you've gotta do what the error says in the title! If you've already run CMake with -G Ninja for example (or without -G for make) but want make (or Ninja), then you have to basically delete the build folder (or at least CMakeCache.txt) and rerun CMake with the appropriate generator flag to switch. If this happens frequently for unknown reasons, then check the settings in your IDE.

The other easy solution is to get into the habit of typing `cmake --build my_build_dir` which will invoke the correct tool based on previous cmake configuration.
