### ISSUE TITLE
GlFont doesn't display in 3D

### ISSUE THREAD

**Issue by b51** [stevenlovegrove/Pangolin#776]
Hello, I got a text display problem in 3D enviroment.
I used to use
`pangolin::GlFont::I().Text(name).Draw(x, y, z)` for adding some information on 3d points. 
After upgrade Pangolin to 0.8 version, `GlFont()::I()` is not avaliable, so I use `pangolin::default_font().Text(name).Draw(x, y, z)` instead, but I cannot get any text display on 3D point any more. Can anyone help solve this?

**Comment by jhch1995** [comment]
> Hello, I got a text display problem in 3D enviroment.
> I used to use
> `pangolin::GlFont::I().Text(name).Draw(x, y, z)` for adding some information on 3d points.
> After upgrade Pangolin to 0.8 version, `GlFont()::I()` is not avaliable, so I use `pangolin::default_font().Text(name).Draw(x, y, z)` instead, but I cannot get any text display on 3D point any more. Can anyone help solve this?

I also meet this problem， do you have solved it?

**Comment by b51** [comment]
> > Hello, I got a text display problem in 3D enviroment.
> > I used to use
> > `pangolin::GlFont::I().Text(name).Draw(x, y, z)` for adding some information on 3d points.
> > After upgrade Pangolin to 0.8 version, `GlFont()::I()` is not avaliable, so I use `pangolin::default_font().Text(name).Draw(x, y, z)` instead, but I cannot get any text display on 3D point any more. Can anyone help solve this?
> 
> I also meet this problem， do you have solved it?

No, not yet. Font can only displayed by rolling pangolin back to v0.6.

**Comment by wenwenqingqing** [comment]
I also confused about this issue.

**Comment by stevenlovegrove** [comment]
Apologies for the slow reply!

https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_opengl/src/gltext.cpp#L137 is the code responsible for this call and it does a few things
* Figure out the 2D Window coordinate corresponding to the 3D position specified. It does this by loading the viewport, modelview and projection matrices. If these matrices are not set up, or if you're not using them (because you are using a shader or something), that will be a problem
* Sets up an appropriate 2D viewport in pixel units to render the text into (font sizes are in pixel units)
* Draws the text (binds the appropriate texture map and sets up the vertex buffer etc)
* Restores the original state matrices.

Assuming that the pangolin examples work to show text (such as SimpleDisplay), there is likely a very small assumption about OpenGL state which is different, since we know that https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/src/widgets.cpp#L59 is working for you. You could try copying the setup code in that class (https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_display/src/widgets.cpp#L264). In particular, getting the blend function right, ensuring you don't have backface culling enabled, disable lighting and you could also try disabling the depth test in case you have some draw ordering issues. Failing that, there is likely something in the 3D to 2D projection step - you could try using the [DrawWindow](https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_opengl/src/gltext.cpp#L176) method to bypass that and go from there.
