### ISSUE TITLE
Prerequisites script wont show me the list of required packages

### ISSUE THREAD

**Issue by alex-fu27** [stevenlovegrove/Pangolin#802]
I hoped to see a list of required packages when I run
```
./scripts/install_prerequisites.sh --dry-run recommended
```
but I get
```
Error: No preferred package managers from list [dnf apt port vcpkg brew] found. Use -m to select manually.
```

Then I tried with `-m apt`, expected the script to output a list of debian packages but got the same error. As you can maybe tell I am neither on Debian, MacOS or whatever.

I think the best solution would be to have a list of required libraries in the README, ideally with version numbers that are known to be working.

**Comment by stevenlovegrove** [comment]
Ah, it was checking if the manually specified manager exists and hence it was failing.

I just pushed https://github.com/stevenlovegrove/Pangolin/commit/5f78f502117b2ff9238ed63768fd859a8fa78ffd which removes that check when you specify it manually. For your needs, you should use the --list option and then it wont even try to run it, it'll just print the packages the manager requires. I don't want to include the list in the readme because it will inevitably become outdated and gets complicated to specify per-platform. I should add the below command as an example though. 

e.g.
`./scripts/install_prerequisites.sh --list recommended -m apt`
`./scripts/install_prerequisites.sh --list recommended -m port`
