### ISSUE TITLE
render_tree T_cam_norm

### ISSUE THREAD

**Issue by guoshuxu** [stevenlovegrove/Pangolin#807]
Hi, according to OpenGL Normal Vector Transformation: http://www.songho.ca/opengl/gl_normaltransform.html, if T_cam_norm should be T_camera_node.Inverse().Transpose()? 

https://github.com/stevenlovegrove/Pangolin/blob/5f78f502117b2ff9238ed63768fd859a8fa78ffd/tools/ModelViewer/rendertree.h#L91

**Comment by guoshuxu** [comment]
@stevenlovegrove

**Comment by stevenlovegrove** [comment]
Firstly, this is for a custom shader, not for the fixed function pipeline, so the notation etc might not necessarily match exactly with what you link, but in fact the maths is the same.

Although we're passing in the full 4x4 matrix (can't remember why I did that), we're only going to use the 3x3 rotation matrix component since the normal is a direction vector (https://github.com/stevenlovegrove/Pangolin/blob/5f78f502117b2ff9238ed63768fd859a8fa78ffd/tools/ModelViewer/shader.h#L29).

For rotation matrices (which are orthonormal), the inverse() is the same as the transpose(). If R_camera_node is the top-left 3x3 matrix of T_camera_node (the part we'll actually use in the shader), 

R_camera_node.Inverse().Transpose() == R_camera_node.Inverse().Inverse() == R_camera_node;

The notation I use for these transforms, T_b_a or R_b_a, is such that when applied to the left of a point in frame a, they transform the point to frame b.

e.g. point_in_camera = T_camera_node * point_in_node.

and similarly for direction vectors, though we must make sure we don't move them and use only the rotation matrix

e.g. dir_in_camera = R_camera_node * dir_in_node.

Songho actually says the same thing in the last paragraph of your link about how it would be more efficient to use a rotation matrix instead of the 4x4 matrix, and how inverse and transpose are the same in that case.
