### ISSUE TITLE
Why is Pangolin rebuilding some files after reconfiguring?

### ISSUE THREAD

**Issue by mholzel** [stevenlovegrove/Pangolin#838]
I would just like a concise explanation for the following behavior so that I know how to mitigate it... 

We have a large project that includes pangolin and a lot of other well-known libraries (e.g. imgui, cilantro, etc. ). We also have a lot of scripts to automate things. 

One of the build scripts looks like this: 

```
BUILD_DIR=build
cmake -B $BUILD_DIR -S . -D CMAKE_BUILD_TYPE=Release
cmake --build $BUILD_DIR --target foobar
```

Basically, just configure and build.

The "issue" is that if you run this script twice in a row, then on the second pass the build tools detect everything as being `built` except for 3 files in pangolin:  
```
[  6%] Built target imgui
[ 20%] Building CXX object submodules/pangolin/src/CMakeFiles/pangolin.dir/display/display.cpp.o
[ 21%] Building CXX object submodules/pangolin/src/CMakeFiles/pangolin.dir/video/video.cpp.o
[ 23%] Building CXX object submodules/pangolin/src/CMakeFiles/pangolin.dir/fonts.cpp.o
[ 23%] Linking CXX static library ../../../lib/libpangolin.a
[ 62%] Built target pangolin
[ 87%] Built target cilantro
```

As you can image, this slows down the build times. 

This might be intended behavior, but I would like to understand why this is happening. 

I assume that the reconfiguration step is invalidating something in the Cmake cache, but I don't know what that is, or how to change the behavior.

**Comment by stevenlovegrove** [comment]
There are a couple of configure-time steps in pangolin which generate source files.

1) Pangolin embeds its font and the shader files it uses into the lib so there are no issues with finding these at runtime (to simplify client code)
https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_opengl/CMakeLists.txt#L7
https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_opengl/CMakeLists.txt#L8

2) Pangolin has a modular factory instantiation mechanism for adding new video providers and windowing providers. It uses CMake to autogenerate source-code to register these components based on which libraries have been detected (instead of having a big if-statement somewhere to pick the right one).
https://github.com/stevenlovegrove/Pangolin/blob/master/components/pango_video/CMakeLists.txt#L31

I guess it should be possible to rewrite these as build-time tasks if this is a big issue in your build. The relevant cmake utils are:
https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/EmbedBinaryFiles.cmake
https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/EmbedShaderFiles.cmake
https://github.com/stevenlovegrove/Pangolin/blob/master/cmake/PangolinFactory.cmake

CMake already tracks cmake files to re-configure when they are changed, so you could alternatively modify your script to only invoke CMake if no cmake cache file exists, letting the makefile reconfigure when actually needed - not sure which is easiest for your use case.

Does that make sense?

**Comment by mholzel** [comment]
Makes perfect sense. Let me dwell on how to proceed. Thanks for the quick response.
